import "./_section-1";
import "./_section-2";
import "./_section-3";
import "./_section-4";
// import "./_section-5";
import "./_section-6";
// import "./_incluzivnii-proekt-section";
import "./_section-8";
import "./_section-9";
import "./_section-10";
import "./_section-11";
import "./_section-12";
