import "./_section-1";
import "./_section-2";
// import "./_section-3";
// import "./_iz-chego-sostoit-section";
// import "./_huliganskii-proekt-section";
// import "./_proftruppa-section";
// import "./_incluzivnii-proekt-section";
import "./_section-8";
import "./_section-9";
import "./_section-10";
import "./_section-11";
import "./_section-12";
